# Use uma imagem base do Node.js
FROM node:14

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos necessários
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante dos arquivos
COPY . .

# Exponha a porta
EXPOSE 4000

# Comando para iniciar o servidor Nest.js
CMD ["npm", "run", "start:prod"]
